
import Foundation

struct Ats: Codable {
	let atsIdent: String? 	let seqNbr: Double? 	let direction: String? 	let type: String? 	let icao: String? 	let bidirect: String? 	let freqClass: String? 	let level: String? 	let status: String? 	let wpt1Icao: String? 	let wpt1NavType: String? 	let wpt1Ident: String? 	let wpt1Ctry: String? 	let wpt1Desc1: String? 	let wpt1Desc2: String? 	let wpt1Desc3: String? 	let wpt1Desc4: String? 	let wpt1WgsLat: String? 	let wpt1WgsDlat: Double? 	let wpt1WgsLong: String? 	let wpt1WgsDlong: Double? 	let wpt2Icao: String? 	let wpt2NavType: Double? 	let wpt2Ident: String? 	let wpt2Ctry: String? 	let wpt2Desc1: String? 	let wpt2Desc2: String? 	let wpt2Desc3: String? 	let wpt2Desc4: String? 	let wpt2WgsLat: String? 	let wpt2WgsDlat: Double? 	let wpt2WgsLong: String? 	let wpt2WgsDlong: Double? 	let outbdCrs: Double? 	let distance: Double? 	let inbdCrs: Double? 	let minAlt: String? 	let upperLimit: String? 	let lowerLimit: String? 	let maa: String? 	let cruiseLevel: String? 	let rnp: String? 	let cycleDate: Double? 	let rvsm: String? 	let fixTurn1: String? 	let fixTurn2: String? 


	enum CodingKeys: String, CodingKey {
		case atsIdent = "ATS_IDENT"		case seqNbr = "SEQ_NBR"		case direction = "DIRECTION"		case type = "TYPE"		case icao = "ICAO"		case bidirect = "BIDIRECT"		case freqClass = "FREQ_CLASS"		case level = "LEVEL"		case status = "STATUS"		case wpt1Icao = "WPT1_ICAO"		case wpt1NavType = "WPT1_NAV_TYPE"		case wpt1Ident = "WPT1_IDENT"		case wpt1Ctry = "WPT1_CTRY"		case wpt1Desc1 = "WPT1_DESC_1"		case wpt1Desc2 = "WPT1_DESC_2"		case wpt1Desc3 = "WPT1_DESC_3"		case wpt1Desc4 = "WPT1_DESC_4"		case wpt1WgsLat = "WPT1_WGS_LAT"		case wpt1WgsDlat = "WPT1_WGS_DLAT"		case wpt1WgsLong = "WPT1_WGS_LONG"		case wpt1WgsDlong = "WPT1_WGS_DLONG"		case wpt2Icao = "WPT2_ICAO"		case wpt2NavType = "WPT2_NAV_TYPE"		case wpt2Ident = "WPT2_IDENT"		case wpt2Ctry = "WPT2_CTRY"		case wpt2Desc1 = "WPT2_DESC_1"		case wpt2Desc2 = "WPT2_DESC_2"		case wpt2Desc3 = "WPT2_DESC_3"		case wpt2Desc4 = "WPT2_DESC_4"		case wpt2WgsLat = "WPT2_WGS_LAT"		case wpt2WgsDlat = "WPT2_WGS_DLAT"		case wpt2WgsLong = "WPT2_WGS_LONG"		case wpt2WgsDlong = "WPT2_WGS_DLONG"		case outbdCrs = "OUTBD_CRS"		case distance = "DISTANCE"		case inbdCrs = "INBD_CRS"		case minAlt = "MIN_ALT"		case upperLimit = "UPPER_LIMIT"		case lowerLimit = "LOWER_LIMIT"		case maa = "MAA"		case cruiseLevel = "CRUISE_LEVEL"		case rnp = "RNP"		case cycleDate = "CYCLE_DATE"		case rvsm = "RVSM"		case fixTurn1 = "FIX_TURN1"		case fixTurn2 = "FIX_TURN2"
}
}