
import Foundation

struct TrmSeg: Codable {
	let arptIdent: String? 	let proc: Double? 	let trmIdent: String? 	let seqNbr: Double? 	let type: Double? 	let transition: String? 	let icao: String? 	let trackCd: String? 	let wptId: String? 	let wptCtry: String? 	let wptDesc1: String? 	let wptDesc2: String? 	let wptDesc3: String? 	let wptDesc4: String? 	let turnDir: String? 	let nav1Ident: String? 	let nav1Type: String? 	let nav1Ctry: String? 	let nav1KeyCd: String? 	let nav1Bear: String? 	let nav1Dist: String? 	let nav2Ident: String? 	let nav2Type: String? 	let nav2Ctry: String? 	let nav2KeyCd: String? 	let nav2Bear: String? 	let nav2Dist: String? 	let magCrs: String? 	let distance: String? 	let altDesc: String? 	let altOne: String? 	let altTwo: String? 	let rnp: String? 	let cycleDate: Double? 	let wptWgsLat: String? 	let wptWgsDlat: Double? 	let wptWgsLong: String? 	let wptWgsDlong: Double? 	let wptMvar: Double? 	let nav1WgsLat: String? 	let nav1WgsDlat: String? 	let nav1WgsLong: String? 	let nav1WgsDlong: String? 	let nav1Mvar: String? 	let nav1DmeWgsLat: String? 	let nav1DmeWgsDlat: String? 	let nav1DmeWgsLong: String? 	let nav1DmeWgsDlong: String? 	let nav2WgsLat: String? 	let nav2WgsDlat: String? 	let nav2WgsLong: String? 	let nav2WgsDlong: String? 	let nav2Mvar: String? 	let nav2DmeWgsLat: String? 	let nav2DmeWgsDlat: String? 	let nav2DmeWgsLong: String? 	let nav2DmeWgsDlong: String? 	let speed: String? 	let speedAc: String? 	let speedAlt: String? 	let speed2: String? 	let speedAc2: String? 	let speedAlt2: String? 	let vnav: String? 	let tch: String? 


	enum CodingKeys: String, CodingKey {
		case arptIdent = "ARPT_IDENT"		case proc = "PROC"		case trmIdent = "TRM_IDENT"		case seqNbr = "SEQ_NBR"		case type = "TYPE"		case transition = "TRANSITION"		case icao = "ICAO"		case trackCd = "TRACK_CD"		case wptId = "WPT_ID"		case wptCtry = "WPT_CTRY"		case wptDesc1 = "WPT_DESC_1"		case wptDesc2 = "WPT_DESC_2"		case wptDesc3 = "WPT_DESC_3"		case wptDesc4 = "WPT_DESC_4"		case turnDir = "TURN_DIR"		case nav1Ident = "NAV1_IDENT"		case nav1Type = "NAV1_TYPE"		case nav1Ctry = "NAV1_CTRY"		case nav1KeyCd = "NAV1_KEY_CD"		case nav1Bear = "NAV1_BEAR"		case nav1Dist = "NAV1_DIST"		case nav2Ident = "NAV2_IDENT"		case nav2Type = "NAV2_TYPE"		case nav2Ctry = "NAV2_CTRY"		case nav2KeyCd = "NAV2_KEY_CD"		case nav2Bear = "NAV2_BEAR"		case nav2Dist = "NAV2_DIST"		case magCrs = "MAG_CRS"		case distance = "DISTANCE"		case altDesc = "ALT_DESC"		case altOne = "ALT_ONE"		case altTwo = "ALT_TWO"		case rnp = "RNP"		case cycleDate = "CYCLE_DATE"		case wptWgsLat = "WPT_WGS_LAT"		case wptWgsDlat = "WPT_WGS_DLAT"		case wptWgsLong = "WPT_WGS_LONG"		case wptWgsDlong = "WPT_WGS_DLONG"		case wptMvar = "WPT_MVAR"		case nav1WgsLat = "NAV1_WGS_LAT"		case nav1WgsDlat = "NAV1_WGS_DLAT"		case nav1WgsLong = "NAV1_WGS_LONG"		case nav1WgsDlong = "NAV1_WGS_DLONG"		case nav1Mvar = "NAV1_MVAR"		case nav1DmeWgsLat = "NAV1_DME_WGS_LAT"		case nav1DmeWgsDlat = "NAV1_DME_WGS_DLAT"		case nav1DmeWgsLong = "NAV1_DME_WGS_LONG"		case nav1DmeWgsDlong = "NAV1_DME_WGS_DLONG"		case nav2WgsLat = "NAV2_WGS_LAT"		case nav2WgsDlat = "NAV2_WGS_DLAT"		case nav2WgsLong = "NAV2_WGS_LONG"		case nav2WgsDlong = "NAV2_WGS_DLONG"		case nav2Mvar = "NAV2_MVAR"		case nav2DmeWgsLat = "NAV2_DME_WGS_LAT"		case nav2DmeWgsDlat = "NAV2_DME_WGS_DLAT"		case nav2DmeWgsLong = "NAV2_DME_WGS_LONG"		case nav2DmeWgsDlong = "NAV2_DME_WGS_DLONG"		case speed = "SPEED"		case speedAc = "SPEED_AC"		case speedAlt = "SPEED_ALT"		case speed2 = "SPEED_2"		case speedAc2 = "SPEED_AC_2"		case speedAlt2 = "SPEED_ALT_2"		case vnav = "VNAV"		case tch = "TCH"
}
}