//
//  Enums.swift
//  unZip
//
//  Created by Matthew Elmore on 5/19/19.
//  Copyright © 2019 Matthew Elmore. All rights reserved.
//

import Foundation

///Enum for the specific subfolder names.
public enum FolderLoc {
    case dafif8
    case dafift
    case json
}

///Enum that Swiftifies the DAFIF8 Text file names.
enum FileNames: String, CaseIterable {
    case vfrRte = "VFR_RTE.TXT"
    case vfrRteSeg = "VFR_RTE_SEG.TXT"
    case vfrRteRmk = "VFR_RTE_RMK.TXT"
    case pja = "PJA.TXT"
    case pjaPar = "PJA_PAR.TXT"
    case ortca = "ORTCA.TXT"
    case irPar = "IR_PAR.TXT"
    case ir = "IR.TXT"
    case irCtry = "IR_CTRY.TXT"
    case arfFt = "ARF_FT.TXT"
    case arfSeg = "ARF_SEG.TXT"
    case arfAtc = "ARF_ATC.TXT"
    case arfRmk = "ARF_RMK.TXT"
    case arfPar = "ARF_PAR.TXT"
    case arfSch = "ARF_SCH.TXT"
    case arfPt = "ARF_PT.TXT"
    case mtrOsm = "MTR_OSM.TXT"
    case mtr = "MTR.TXT"
    case mtrOv = "MTR_OV.TXT"
    case mtrRmk = "MTR_RMK.TXT"
    case mtrPar = "MTR_PAR.TXT"
    case suasPar = "SUAS_PAR.TXT"
    case suas = "SUAS.TXT"
    case suasNote = "SUAS_NOTE.TXT"
    case suasCtry = "SUAS_CTRY.TXT"
    case ils = "ILS.TXT"
    case rwy = "RWY.TXT"
    case arptRmk = "ARPT_RMK.TXT"
    case acom = "ACOM.TXT"
    case arpt = "ARPT.TXT"
    case acomRmk = "ACOM_RMK.TXT"
    case anav = "ANAV.TXT"
    case agear = "AGEAR.TXT"
    case trmRmk = "TRM_RMK.TXT"
    case trmClb = "TRM_CLB.TXT"
    case trmSeg = "TRM_SEG.TXT"
    case trmMin = "TRM_MIN.TXT"
    case trmMsa = "TRM_MSA.TXT"
    case trmPar = "TRM_PAR.TXT"
    case trmFdr = "TRM_FDR.TXT"
    case pad = "PAD.TXT"
    case hnav = "HNAV.TXT"
    case hlptRmk = "HLPT_RMK.TXT"
    case hlpt = "HLPT.TXT"
    case hcom = "HCOM.TXT"
    case hcomRmk = "Hcom_RMK.TXT"
    case appcSuasWx = "APPC_SUAS_WX.TXT"
    case appcComSymbols = "APPC_COM_SYMBOLS.TXT"
    case appcPrAcftType = "APPC_PR_ACFT_TYPE.TXT"
    case appcNavType = "APPC_NAV_TYPE.TXT"
    case appcAbsorbingSys = "APPC_ABSORBING_SYS.TXT"
    case appcTrmTrackCd = "APPC_TRM_TRACK_CD.TXT"
    case appcComType = "APPC_COM_TYPE.TXT"
    case appcLevel = "APPC_LEVEL.TXT"
    case appcFluids = "APPC_FLUIDS.TXT"
    case appcAtsWptDesc1 = "APPC_ATS_WPT_DESC_1.TXT"
    case appcIlsCat = "APPC_ILS_CAT.TXT"
    case appcUsStateCodes = "APPC_US_STATE_CODES.TXT"
    case appcAtsFreqClass = "APPC_ATS_FREQ_CLASS.TXT"
    case appcTrmType = "APPC_TRM_TYPE.TXT"
    case appcFuelCodes = "APPC_FUEL_CODES.TXT"
    case appcAtsWptDesc2 = "APPC_ATS_WPT_DESC_2.TXT"
    case appcEngagingDev = "APPC_ENGAGING_DEV.TXT"
    case appcPrPtType = "APPC_PR_PT_TYPE.TXT"
    case appcTrmNavType = "APPC_TRM_NAV_TYPE.TXT"
    case appcCcIcao = "APPC_CC_ICAO.TXT"
    case appcAtsWptDesc3 = "APPC_ATS_WPT_DESC_3.TXT"
    case appcMtrCrsAlt = "APPC_MTR_CRS_ALT.TXT"
    case appcAtsStatus = "APPC_ATS_STATUS.TXT"
    case appcBdryType = "APPC_BDRY_TYPE.TXT"
    case appcAtsWptDesc4 = "APPC_ATS_WPT_DESC_4.TXT"
    case appcHeliType = "APPC_HELI_TYPE.TXT"
    case appcMtrUsageCd = "APPC_MTR_USAGE_CD.TXT"
    case appcWptType = "APPC_WPT_TYPE.TXT"
    case appcIlsCompType = "APPC_ILS_COMP_TYPE.TXT"
    case appcWptUsageCd = "APPC_WPT_USAGE_CD.TXT"
    case appcOils = "APPC_OILS.TXT"
    case appcArDir = "APPC_AR_DIR.TXT"
    case appcDerivation = "APPC_DERIVATION.TXT"
    case appcArUsageCd = "APPC_AR_USAGE_CD.TXT"
    case appcRwySfcCodes = "APPC_RWY_SFC_CODES.TXT"
    case appcAtsType = "APPC_ATS_TYPE.TXT"
    case appcRwyLgtCodes = "APPC_RWY_LGT_CODES.TXT"
    case appcNavStatus = "APPC_NAV_STATUS.TXT"
    case appcPjaType = "APPC_PJA_TYPE.TXT"
    case appcNavRcc = "APPC_NAV_RCC.TXT"
    case appcOprAgcy = "APPC_OPR_AGCY.TXT"
    case appcArType = "APPC_AR_TYPE.TXT"
    case appcTrmProc = "APPC_TRM_PROC.TXT"
    case appcTrmWptDesc3 = "APPC_TRM_WPT_DESC_3.TXT"
    case appcTrmWptDesc2 = "APPC_TRM_WPT_DESC_2.TXT"
    case appcShape = "APPC_SHAPE.TXT"
    case appcComFreqUnit = "APPC_COM_FREQ_UNIT.TXT"
    case appcTrmWptDesc1 = "APPC_TRM_WPT_DESC_1.TXT"
    case appcDaylightSav = "APPC_DAYLIGHT_SAV.TXT"
    case appcJasu = "APPC_JASU.TXT"
    case appcArptType = "APPC_ARPT_TYPE.TXT"
    case appcAcftCap = "APPC_ACFT_CAP.TXT"
    case appcPjaOprTime = "APPC_PJA_OPR_TIME.TXT"
    case appcTrmWptDesc4 = "APPC_TRM_WPT_DESC_4.TXT"
    case appcNavUsageCd = "APPC_NAV_USAGE_CD.TXT"
    case appcLclHorizDatums = "APPC_LCL_HORIZ_DATUMS.TXT"
    case appcIlsColctn = "APPC_ILS_COLCTN.TXT"
    case appcAltitudeDesc = "APPC_ALTITUDE_DESC.TXT"
    case appcSuasType = "APPC_SUAS_TYPE.TXT"
    case pr = "PR.TXT"
    case prPar = "PR_PAR.TXT"
    case wpt = "WPT.TXT"
    case papp = "PAPP.TXT"
    case nav = "NAV.TXT"
    case bdry = "BDRY.TXT"
    case bdryCtry = "BDRY_CTRY.TXT"
    case bdryPar = "BDRY_PAR.TXT"
    case atsRmk = "ATS_RMK.TXT"
    case atsCtry = "ATS_CTRY.TXT"
    case ats = "ATS.TXT"
    case fuelOil = "FUELOIL.TXT"
    case svcRmk = "SVC_RMK.TXT"
    case addRwy = "ADD_RWY.TXT"
    case gen = "GEN.TXT"
    case tzPar = "TZ_PAR.TXT"
    case hold = "HOLD.TXT"
    
}
